<?php

# FILE GENERATED by mindplay/composer-locator @ 2016-04-19 16:01:56

/**
 * @return string absolute root path to package installation folder
 *
 * @throws RuntimeException if the specific package is not installed
 */
function composer_path($name) {
    static $paths = array (
  'mindplay/composer-locator' => 'C:\\workspace\\test\\composer-locator-test\\vendor/mindplay/composer-locator',
);

    if (!isset($paths[$name])) {
        throw new RuntimeException('Composer package not found: ' . $name);
    }

    return $paths[$name];
}
