<?php

## FILE GENERATED by mindplay/composer-locator @ $DATE
##
## This file will be auto-generated and overwritten at installation.

abstract class ComposerLocator
{
    /**
     * @var array<string,string> map where Composer vendor/package name => package path (relative to project root path)
     */
    private static $paths = $PATHS;

    /**
     * @param string $name Composer vendor/package name
     *
     * @return string absolute root path to package installation folder
     *
     * @throws RuntimeException if the specific package is not installed
     * 
     * @deprecated in favor of composer-runtime-api
     * @link https://getcomposer.org/doc/07-runtime.md#knowing-the-path-in-which-a-package-is-installed
     */
    public static function getPath(string $name): string
    {
        $name = strtolower($name);

        if (! isset(static::$paths[$name])) {
            throw new RuntimeException("Composer package not found: {$name}");
        }

        return static::getRootPath() . static::$paths[$name];
    }

    /**
     * @return string absolute root path of Composer project
     * 
     * @deprecated in favor of composer-runtime-api: give your package a name and use `\Composer\InstalledVersions::getInstallPath('vendor/package')` instead
     * @link https://getcomposer.org/doc/07-runtime.md#knowing-the-path-in-which-a-package-is-installed
     */
    public static function getRootPath(): string
    {
        return dirname(__DIR__, 4);
    }
    
    /**
     * @param string $name Composer vendor/package name
     *
     * @return bool true, if the given package is installed
     * 
     * @deprecated in favor of composer-runtime-api
     * @link https://getcomposer.org/doc/07-runtime.md#knowing-whether-package-x-or-virtual-package-is-present
     */
    public static function isInstalled(string $name): bool
    {
        return isset(static::$paths[$name]);
    }

    /**
     * @return string[] list of "vendor/package" names
     * 
     * @deprecated in favor of composer-runtime-api: use e.g. `\Composer\InstalledVersions::getInstalledPackagesByType('library')` instead
     * @link https://getcomposer.org/doc/07-runtime.md#knowing-which-packages-of-a-given-type-are-installed
     */
    public static function getPackages(): array
    {
        return array_keys(static::$paths);
    }

    /**
     * @return array<string,string> map where Composer vendor/package name => absolute root path
     * 
     * @deprecated in favor of composer-runtime-api: use e.g. `\Composer\InstalledVersions::getInstalledPackagesByType('library')` instead
     * @link https://getcomposer.org/doc/07-runtime.md#knowing-which-packages-of-a-given-type-are-installed
     */
    public static function getPaths(): array
    {
        $paths = [];
        
        foreach (static::$paths as $name => $path) {
            $paths[$name] = static::getRootPath() . $path;
        }
        
        return $paths;
    }
}
