name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
    steps:
      - uses: shivammathur/setup-php@2.30.4
        with:
          php-version: ${{ matrix.php }}
      - uses: actions/checkout@v4
      - run: composer update --no-interaction --prefer-dist
      - run: composer run test
